// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcWDqLqD8SDTU-qSTDy6pWlvQePce03Pk',
    appId: '1:56846633253:web:c408faad866dabdfe1b2cc',
    messagingSenderId: '56846633253',
    projectId: 'newsapp-13',
    authDomain: 'newsapp-13.firebaseapp.com',
    storageBucket: 'newsapp-13.firebasestorage.app',
    measurementId: 'G-5TT2PFD6VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9NmowggDqDJDy8PZCd9KdVklNwHkKCVk',
    appId: '1:56846633253:android:ad4c26b0bc4c1e2ee1b2cc',
    messagingSenderId: '56846633253',
    projectId: 'newsapp-13',
    storageBucket: 'newsapp-13.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcWDqLqD8SDTU-qSTDy6pWlvQePce03Pk',
    appId: '1:56846633253:web:da25566ec5523bbfe1b2cc',
    messagingSenderId: '56846633253',
    projectId: 'newsapp-13',
    authDomain: 'newsapp-13.firebaseapp.com',
    storageBucket: 'newsapp-13.firebasestorage.app',
    measurementId: 'G-QXKXNZGSKR',
  );

}